// Anti-aliased bitmap fonts ("HFN4", generated by tools/make_assets.py)
#pragma once

#include <stddef.h>
#include <stdint.h>
#include <string>
#include <vector>

#include "gfx.h"

struct Font {
	bool load(const void *data, size_t size);

	int lineHeight() const { return _lineHeight; }
	// Font used for characters this one doesn't have
	void setFallback(const Font *f) { _fallbackFont = f; }
	int ascent() const { return _ascent; }

	int advance(uint32_t cp) const;
	int width(const char *utf8, int len = -1) const;
	int width(const std::string &s) const { return width(s.c_str(), (int)s.size()); }

	// Draws text with its top-left corner at (x, y). Returns the final pen x.
	int draw(Surface &s, int x, int y, const char *utf8, uint16_t color, int alpha = 255, int len = -1) const;
	int draw(Surface &s, int x, int y, const std::string &t, uint16_t color, int alpha = 255) const {
		return draw(s, x, y, t.c_str(), color, alpha, (int)t.size());
	}
	void drawCentered(Surface &s, int cx, int y, const std::string &t, uint16_t color, int alpha = 255) const;
	void drawRight(Surface &s, int rx, int y, const std::string &t, uint16_t color, int alpha = 255) const;
	// Draws text cut to maxWidth, with "…" at the end if needed
	void drawEllipsized(Surface &s, int x, int y, const std::string &t, int maxWidth, uint16_t color, int alpha = 255) const;
	std::string ellipsize(const std::string &t, int maxWidth) const;

	// Word-wraps text to maxWidth. Honours '\n'.
	void wrap(const std::string &t, int maxWidth, std::vector<std::string> &lines) const;
	// Draws wrapped text, returns the height used
	int drawWrapped(Surface &s, int x, int y, const std::string &t, int maxWidth, uint16_t color, int maxLines = 0) const;

private:
	struct Glyph {
		int8_t xoff, yoff;
		uint8_t w, h, adv, pad0;
		uint16_t pad1;
		uint32_t offset;
	};

	int find(uint32_t cp) const;

	int _lineHeight = 0, _ascent = 0, _count = 0;
	const uint16_t *_codepoints = nullptr;
	const Glyph *_glyphs = nullptr;
	const uint8_t *_data = nullptr;
	int _fallback = -1;
	const Font *_fallbackFont = nullptr;
};

// Decodes one UTF-8 code point and advances p (never past end)
uint32_t utf8Next(const char *&p, const char *end);
void utf8Append(std::string &out, uint32_t cp);

namespace fonts {
extern Font body, bold, title, head, huge;
bool init();
} // namespace fonts
